name: build-werkernel

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'WER_Kernel/**'
      - 'WER_Kernel.sln'
      - '.github/workflows/build-werkernel.yml'

concurrency:
  group: build-werkernel-${{ github.ref }}
  cancel-in-progress: false

jobs:
  win-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build (x64 Release)
        run: msbuild WER_Kernel.sln /m /p:Configuration=Release /p:Platform=x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WER_Kernel-x64-Release
          path: |
            **/x64/Release/*.exe
            **/x64/Release/*.pdb
          if-no-files-found: error
          retention-days: 30
